### ISSUE TITLE
Post SoundCloud extension on BabelZilla

### ISSUE THREAD

**Issue by AntoineTurmel** [kruppel/soundcloud#14]
You should post SoundCloud extension on BabelZilla using Songbird credentials ;)

**Comment by kruppel** [comment]
Already had that in mind ;) (except with my own creds). FWIW, most strings are set to localize. Still needs some cleanup here and there...

However, I'll probably wait for the app to get posted to http://soundcloud.com/apps before sending it out to Babelzilla (in case major changes need to be made).

**Comment by AntoineTurmel** [comment]
Any update ?
