### ISSUE TITLE
Already logged in user experiences login fail

### ISSUE THREAD

**Issue by kruppel** [kruppel/soundcloud#22]
Submitted by nokia5230:

"We can't verify that you came here from a page or application affiliated with Songbird. Please make sure that this is the case before approving access."

so i click connect after verifying my details, it says account connected, but then doesn't actually log me in. The icon in the bottom right remains grey, and still prompts me to login. :/

**Comment by nokia5230** [comment]
hi,

im runing vista,
latest songbird client, with all the recomended plugins (the ones it reccomends you when you first install it) + soundcloud + gonzo 2 skin + last fm sidebar,

screenshots: 
http://www.flickr.com/photos/46796114@N08/

this process does nothing though.

what other info do you need?

ta.

**Comment by nokia5230** [comment]
on going through the other github issues you have, i seem to have the same issue describes by

https://github.com/kruppel/soundcloud/issues/21

if that helps.

thanks.

**Comment by kruppel** [comment]
What version of the addon are you using?

**Comment by nokia5230** [comment]
hi, 1.0.3+dev-201105050000

at the end of last night it was working ok, but as of this morning it wont login again.

**Comment by kruppel** [comment]
It's working fine for me. Is there anything SoundCloud-related dumped to the error console (I'm only interested in errors, not warnings)?

**Comment by nokia5230** [comment]
hi  sorry not to respond,
It would appear to be working fine again. which is very odd because songbird hasn't done any upgrades to anything in the mean time.
It does dump an error JASON.parse, but i haven't had the error since it has been working again.

**Comment by kruppel** [comment]
Sweet. Closing this out then. Feel free to re-open if you experience the issue in the future. In case you do see a JSON.parse error again, copy and paste the error console row information here (I need the erring file and line number in particular). Thanks again for being proactive.
